// react-mfe/src/App.tsx
import React, { useState } from "react";

export default function Root(props) {
  const [count, setCount] = useState(0);

  return (
    <div
      style={{
        border: "2px solid blue",
        borderRadius: "5px",
        padding: "20px",
        margin: "10px",
      }}
    >
      <h2>React Micro Frontend</h2>
      <p>
        This component is built with React and exposed through both single-spa
        and Module Federation
      </p>

      <div>
        <p>Counter: {count}</p>
        <button onClick={() => setCount(count + 1)}>Increment</button>
      </div>
    </div>
  );
}

// vue-mfe/src/App.vue
<template>
  <div class="vue-container">
    <h2>Vue Micro Frontend</h2>
    <p>This component is built with Vue and exposed through both single-spa and Module Federation</p>
    
    <div>
      <p>Counter: {{ count }}</p>
      <button @click="increment">Increment</button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      count: 0
    };
  },
  methods: {
    increment() {
      this.count += 1;
    }
  }
};
</script>

<style scoped>
.vue-container {
  border: 2px solid green;
  border-radius: 5px;
  padding: 20px;
  margin: 10px;
}
</style>
